name: Unzip uploaded ZIP file to root

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip all .zip files to root
        run: |
          for file in $(find . -name '*.zip'); do
            unzip -o "$file" -d .
            rm "$file"
          done

      - name: Commit unzipped content
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped arch
