name: Unzip uploaded file

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip all zip files
        run: |
          for file in $(find . -main '*.zip'); do
            unzip -o "$file" -d "${file%.*}"
          done

      - name: Commit unzipped content
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped archive(s)"
          git push